[package]
name = "typio-engine-basic"
version = "0.0.1"
edition = "2021"
authors = ["Typio Contributors"]
license = "MIT"

[dependencies]
libc = "0.2"
typio-abi = { path = "../libtypio/crates/abi" }

[dev-dependencies]
typio-devlint = { path = "../typio-devlint" }

[lib]
name = "typio_engine_basic"
crate-type = ["cdylib"]
